# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

exclude: ["README.md", "License.md", "random-website.Rproj"]
highlighter: rouge

title: random-website
author:
  name: Ivan Hanigan
  email: ivan.hanigan@gmail.com
  github: ivanhanigan

url: https://ivanhanigan.github.io

baseurl: /random-website

